---
apiVersion: v1
kind: Template
labels:
  template: "${APP_LABEL}-email-microsrv-bc"
metadata:
  name: "${APP_LABEL}-email-microsrv-bc"
objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: "${APP_LABEL}"
    name: "${IMAGE_NAME}"
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: "${APP_LABEL}"
    name: "${IMAGE_NAME}"
  spec:
    completionDeadlineSeconds: 600
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: "${IMAGE_NAME}:latest"
    postCommit: {}
    resources:
      requests:
        cpu: "${CPU_REQUEST}"
        memory: "${MEMORY_REQUEST}"
      limits:
        cpu: "${CPU_LIMIT}"
        memory: "${MEMORY_LIMIT}"
    runPolicy: Serial
    source:
      contextDir: /api
      git:
        ref: "${SOURCE_REPO_REF}"
        uri: "${SOURCE_REPO_URL}"
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:12
          namespace: openshift
        incremental: true
    successfulBuildsHistoryLimit: 5

parameters:
- name: SOURCE_REPO_URL
  description: Git Repository URL
  required: true
  value: https://github.com/bcgov/nr-email-microservice.git
- name: SOURCE_REPO_REF
  description: Check out a specific Git reference. A valid ref can be a SHA1 tag (i.e. 'release-1.0.0') or a branch name (i.e. 'master'), or pull request ref. (i.e. 'pull/CHANGE_ID/head')
  required: true
  value: master
- name: APP_LABEL
  description: Application name, will be used for metadata and label=APP_LABEL
  required: true
  value: email-microsrv
- name: IMAGE_NAME
  description: Name to use for the image
  value: email-microsrv-api
- name: CPU_REQUEST
  description: Requested CPU per pod (in millicores ex. 500m)
  required: true
  value: 500m
- name: MEMORY_REQUEST
  description: Requested Memory per pod (in gigabytes Gi or megabytes Mi ex. 500Mi)
  required: true
  value: 1Gi
- name: CPU_LIMIT
  description: Limit Peak CPU per pod (in millicores ex. 1000m)
  required: true
  value: 1000m
- name: MEMORY_LIMIT
  description: Limit Peak Memory per pod (in gigabytes Gi or megabytes Mi ex. 2Gi)
  required: true
  value: 2Gi
